[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_dex = "p7naqtynAgMUMWiD6DvG8yYKbuBpGKsn8HtHGn1mT67"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/k0r1/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
